### PR TITLE
Add a list of reasons why the previewer may not be working.

### PR DESCRIPTION
**Pull request by bratsche**
This is regarding issue #175

### CODE REVIEW

**Comment by paulcsmith** [comment]
This looks great. I'll pull this down and see how it looks when it's actually rendered in a browser. Assuming that looks good I'll merge it in!

**Comment by bratsche** [comment]
ping, any update?

**Comment by paulcsmith** [comment]
@bratsche I was sick last week so I didn't have a chance to look. I'll try to check it out today though! Thanks for the ping!

**Comment by paulcsmith** [comment]
I pulled it up and I think I'll need to style this a bit, but I'll go ahead and merge this in because the content is great. Thank you so much! I'll tackle the style stuff in a separate issue

**Pull request merged**
