### PR TITLE
Update mime package version

### LINKED ISSUE #626: Failed to use "mime" because
I am trying to install the dependencies of the the bamboo and bamboo_smtp.
And I am getting this error:
```
Failed to use "mime" because
bamboo (version 2.2.0) requires ~> 1.4
mix.lock specifies 2.0.1

** (Mix) Hex dependency resolution failed, change the version requirements of your dependencies or unlock them (by using mix deps.update or mix deps.unlock). If you are unable to resolve the conflicts you can try overriding with {:dependency, "~> 1.0", override: true}
```

Elixir 1.12.2
Phoenix v1.5.10

### PR DESCRIPTION
**Pull request by tameribrahim**
Fix #626

### CODE REVIEW

**Comment by jtrees** [comment]
Would love to see this merged.

**Comment by germsvel** [comment]
I'm no longer the maintainer of Bamboo, but I can still make small changes like this one. Thanks for the PR!

**Comment by jtrees** [comment]
Sweet, thanks!

**Comment by jtrees** [comment]
@germsvel I just noticed you merged this into `master`. The primary branch is now set to `main` though. Was that deliberate?

**Comment by germsvel** [comment]
@jtrees not intentional at all! Thanks for pointing it out. The PR was opened against `master`, so merging it was merged to `master`. Any chance someone can open the same PR against `main`?

**Comment by jtrees** [comment]
Yup: #635

**Comment by germsvel** [comment]
Thanks!

**Pull request merged**
