### PR TITLE
added support for categories and supporting tests

### PR DESCRIPTION
**Pull request by coryt**
This PR adds categories support to the sendgrid adapter as mentioned in #335

### CODE REVIEW

**Comment by apbendi** [comment]
We are using Bamboo in production and would be interested in this feature. I'm going to be checking out @coryt's fork, but we'd love to see it merged upstream and would be willing to help maintain it as much as possible.

**Comment by jhsbeat** [comment]
I hope the PR could be merged upstream and in use. :)

**Comment by san650** [comment]
Are you considering into merge this PR? Having categories for Sendgrid out of the box would amazing.

**Comment by vinnyalfieri** [comment]
This would be awesome to have.

**Comment by jhsbeat** [comment]
This categories are very dependent to Sendgrid. It should be merged if Banboo wants to support the official Sendgrid v3 Api.

**Comment by apbendi** [comment]
As a datapoint for the maintainers, we rebased this PR's branch to master and have been using it in production for over a week now without issues.

**Comment by san650** [comment]
> This categories are very dependent to Sendgrid. It should be merged if Banboo wants to support the official Sendgrid v3 Api.

@jhsbeat yes, I know. Because the official bamboo adapter for Sendgrid is built in into bamboo itself, I think it should strive to support the official Sendgrid v3 Api 😃

**Comment by paulcsmith** [comment]
Awesome work, and thanks for chiming in @apbendi I'll go ahead and merge this!

**Pull request merged**
