### PR TITLE
Added support for dynamic_template_data to SendGrid

### PR DESCRIPTION
**Pull request by Aleksion**
The newly launched Dynamic Templates on sendgrid requires all data to be added to the dynamic_template_data json structure in the personalization map. 
I've added new helper functions that work similarly to substitute to achieve this.

```elixir

email
|> with_template(@template_id)
|> add_dynamic_field(:user, %{first_name: "jon", email: "jon@snow.com"})
```

### CODE REVIEW

**Comment by Aleksion** [comment]
The tests DOESN'T fail - is something amiss with the circleci currently?

**Comment by Stratus3D** [comment]
My application needs these changes as it requires SendGrid's dynamic transactional templates. Is there anything I can do to help this get merged? And besides the build failure, is there anything else that needs to be done before this can be merged?

**Comment by Aleksion** [comment]
Hi @Stratus3D  - It seems the team is a bit slow to respond currently. You can download my fork if you need it now, and switch over once they update it here. 
```elixir
  {:bamboo, git: "https://github.com/Aleksion/bamboo.git"}
```

**Comment by joshchernoff** [comment]
You should pull from upstream to make sure the build it passing. Otherwise 👍

**Comment by Aleksion** [comment]
@joshchernoff got upstream pulled in

**Comment by mackshkatz** [comment]
Any update on this? I would love to have this merged in soon, but I suppose in the mean time I can use @Aleksion 's fork, thanks for that!

**Comment by Aleksion** [comment]
@joshchernoff  bump

**Comment by joshchernoff** [comment]
> @joshchernoff bump

Sorry but I'm not someone who can merge this PR.

**Comment by Aleksion** [comment]
Sorry about that! :)

 @mjankowski can you merge this?

**Pull request merged**
