### PR TITLE
Resolve #596 : add support for enabling sendgrid click tracking

### LINKED ISSUE #596: Click Tracking settings for SendGrid Adapter
SendGrid allows for click tracking to be enabled/disabled on a per email basis:

https://sendgrid.com/docs/ui/account-and-settings/tracking/#click-tracking

image

I imagine this could be implemented in the same fashion as the current Google Analytics settings support (https://github.com/thoughtbot/bamboo/pull/462)

I'd be happy to open PR for this!

### PR DESCRIPTION
**Pull request by sreecodeslayer**
Close #596

### CODE REVIEW

**Comment by danadaldos** [comment]
Our organization is also hoping this gets merged soon! We opened https://github.com/thoughtbot/bamboo/issues/596.

**Review by danadaldos — APPROVED** [review]
@germsvel - Hey! I don't know if you're still maintaining this library, but I have looked over @sreecodeslayer's implementation here and it's basically identical to Joydrive's implementation on our forked branch. I can attest that this strategy works in production, although ours is slightly different, in that we break out the `click_tracking_enabled_text` and allow that to be passed-in also. I don't think this is critical. I approve!

Ours:
```elixir
  defp put_click_tracking(body, %Email{
         private: %{click_tracking_enabled: enabled, click_tracking_enabled_text: enabled_text}
       }) do
    click_tracking = %{enable: enabled, enabled_text: enabled_text}

    tracking_settings =
      body
      |> Map.get(:tracking_settings, %{})
      |> Map.put(:click_tracking, click_tracking)

    body
    |> Map.put(:tracking_settings, tracking_settings)
  end

  defp put_click_tracking(body, _), do: body
  ```
  
  
  ```elixir
    def with_click_tracking(email, enabled, enabled_text)
      when is_boolean(enabled) and is_boolean(enabled_text) do
    email
    |> Email.put_private(@click_tracking_enabled, enabled)
    |> Email.put_private(@click_tracking_enabled_text, enabled_text)
  end

  def with_click_tracking(_email, _enabled, _enabled_text) do
    raise "expected with_click_tracking enabled/enabled_text parameters to be booleans"
  end
  ```

**Comment by germsvel** [comment]
@danadaldos unfortunately, I haven't had much time to maintain Bamboo since leaving thoughtbot. 

But I just gave this a look, and it looks good to me! Thanks for contributing @sreecodeslayer!

**Comment by danadaldos** [comment]
@germsvel Thank you!

**Pull request merged**
