### PR TITLE
sendgrid helper link working

### PR DESCRIPTION
**Pull request by decentname**
Readme updated with correct link to sendgrid helper docs.

### CODE REVIEW

**Comment by dbernheisel** [comment]
@decentname  Thanks!

**Comment by paulcsmith** [comment]
@dbernheisel I think this should be reverted or we need to make an issue to remind us to change it back before we release 1.0 because we renamed the module: https://github.com/thoughtbot/bamboo/blob/master/lib/bamboo/adapters/send_grid_helper.ex#L1

**Comment by dbernheisel** [comment]
Thanks @paulcsmith. That's tough, because folks have run into problems because of the disparity between master and the published version. What do you think of editing the readme to point to both versions until 1.0?

**Comment by paulcsmith** [comment]
@dbernheisel Yeah pointing to both sounds like a good idea to me

**Pull request merged**
