### PR TITLE
Bamboo.Email - support reply_to 

### PR DESCRIPTION
**Pull request by technicalcapt**
#302

### CODE REVIEW

**Comment by samhamilton** [comment]
@paulcsmith - is there any else we can do to help get this merged?

**Comment by technicalcapt** [comment]
@paulcsmith Thanks - Just try it again and it's working!. You can close #302

**Comment by paulcsmith** [comment]
Awesome! I’m glad it’s working for you :)

**Comment by markmark206** [comment]
i ran into a problem with the approach of 

```
...
|> put_header("reply-to", "foo@bar.com")
...
```

, when username / email address has special characters in it. 

In this case, the DKIM signature that my mailing service (Amazon SES) attaches to the email is deemed invalid by the receiving mailing service (i tested with gmail and hotmail).

For example, if my `reply-to` header looks like this: 
```
...
|> put_header("reply-to", "MarkMark 🍕🧃🎮 <redacted my gmail address@gmail.com>")
...
```

, gmail flags an invalid DKIM signature. I can see this In the "original email" view:

image

Removing special characters from the string fixes the problem. 

image

I am using Amazon SES with Bamboo.SMTPAdapter:

```elixir
  config :my_app, MyApp.Mailer.Bamboo,
    adapter: Bamboo.SMTPAdapter,
    server: "email-smtp.#{aws_region}.amazonaws.com",
...
```

Supplying the same user name / address as a tuple to the `from` field works just fine: 

```elixir
    new_email(
      from: {"MarkMark 🍕🧃🎮", "foo@example.com"},
      ...
```

A possible workaround is to simply use a bare email address in the `reply-to` header.

**Pull request closed without merging**
