### PR TITLE
Add deps badge to README

### PR DESCRIPTION
**Pull request by rrrene**
Heeeeello Thoughtbot,

I'd like to pitch you a new Elixir related badge:

[Deps Status](https://beta.hexfaktor.org/github/thoughtbot/bamboo)

It shows you an analysis for your dependencies. Behind the badge works a CI service written in Elixir which can notify you whenever important updates for your Hex packages are released.

This is still in its infancy, and I want to basically invite you to join the beta to test-drive this. I really believe that we can create a great service for the community with this. That said, don't feel any obligation to accept the PR. You can't hurt my feelings by voicing your honest opinion about this idea!

### CODE REVIEW

**Comment by paulcsmith** [comment]
Hi @rrrene!

Can you define what "important updates" are for Hex packages? What happens when there are important updates, does the badge turn a different color?

I'd love to help out, but I think having a bit more information first would be wonderulf!

**Comment by rrrene** [comment]
Important updates here means those which do no longer fall under your Mix deps requirements. 

Example: bamboo dependents on `{:plug, "~> 1.0"}` so you would get notified when Plug `v2.0.0` is released. Since it is a `:prod` dependency, a chunk of the badge would turn orange.

More information on how the badge might turn out: https://beta.hexfaktor.org/help/badge

You then *optionally* can subscribe to these updates via email. Every user can configure those individually per project and per branch. You can also choose whether you want a weekly summary or daily updates as soon as updates occur (with a max of 1 email per day).

That's basically the current "elevator pitch" for this :grin:

**Comment by paulcsmith** [comment]
@rrrene I think this is an interesting idea, but I feel that the colors are a bit hard to figure out without referencing the documentation. I think this might be more interesting to me as a service that sent an email to me, or that opened up an issue on the project. I think as a badge it is not quite as helpful. 

I'm going to close this, but feel free to leave comments here if you have others ideas or questions. I'd be happy to try something out that sends an email or opens an issue :D

**Comment by rrrene** [comment]
First, let me thank you for considering. I know from experience that time is an assets often undervalued in open-source.

That said, I can't help but feel baffled by your response. In my first reply I wrote

> You [...] can subscribe to these updates via email. [...] You can [get] daily updates as soon as updates occur (with a max of 1 email per day).

to which you respond

> I think this might be more interesting to me as a service that sent an email to me, [...] I'd be happy to try something out that sends an email

o_O

Just to re-iterate: The *value of the service* lies in sending emails with a frequency of your choosing. The *value of the badge* lies in showing potential users of your library that your deps are up-to-date.

**Comment by paulcsmith** [comment]
@rrrene Thank you for clarifying :) I read your response a few weeks ago and did not read it carefully enough/my memory was faulty.  Sorry about that.

What was and is a bit unclear is whether I can get those email updates without the badge. I signed in and hooked it up to my GitHub and I'm now monitoring without the badge. So I assume that will work, but the home page and help pages aren't clear on that. I hope that feedback helps :D Thanks for making a service to help out open source maintainers.

I'm excited to see how it works!

**Comment by rrrene** [comment]
:+1: Testing the actual service, along with giving feedback (like you just did on the onboarding-experience) is actually more valuable than displaying the badge 

:grin: I just use those to start conversations in pull requests.

**Comment by paulcsmith** [comment]
Haha that's smart! The badge definitely got the conversation started. I'll let you know if I have any other feedback in the future :D

**Pull request closed without merging**
