### PR TITLE
Possible send custom args in SendGridAdapter

### PR DESCRIPTION
**Pull request by clairton**

### CODE REVIEW

**Comment by joshchernoff** [comment]
Could you please provide some test coverage that utilize the code committed? My last pr was to fix a bug most likely due to someone adding code that was not covered by the tests.

**Comment by clairton** [comment]
ci is failing on apt update on OS yet.

**Comment by clairton** [comment]
ping =)

**Comment by paulcsmith** [comment]
I'm re-running the specs now that Circle has been updated. Once it passes, I'll merge this in!

**Comment by clairton** [comment]
It works! 👍

**Comment by paulcsmith** [comment]
Woo hoo!

**Pull request merged**
