### PR TITLE
Add hackney options support to config

### PR DESCRIPTION
**Pull request by tmarkanov**
Add hackney options support to config, e.g.:
```
config :agora, MyApp.Mailer,
  adapter: Bamboo.MandrillAdapter,
  api_key: "x",
  hackney: [
    recv_timeout: 5 * 60 * 1000
  ]
```
Added in order to circumvent https://github.com/thoughtbot/bamboo/issues/299, i.e. to enable setting of `recv_timeout` in order to be able to send larger attachments without errors.

### CODE REVIEW

**Comment by maymillerricci** [comment]
Thanks for this! What do you think about adding some tests to verify that the configuration works as expected?

**Comment by tmarkanov** [comment]
Sure thing! I am a bit busy at the moment but will try to do it as soon as I can.

**Comment by mtarnovan** [comment]
Ups, I overlooked this PR when i opened https://github.com/thoughtbot/bamboo/pull/498

**Comment by mtarnovan** [comment]
@maymillerricci @tmarkanov if that's ok with you we can close this in favor of #498 which is basically the same thing, but has more some docs. Re: May's comment about verifying the configuration works as expected, on the other PR that's done through a helper that's also tested. How would you suggest to verify the configuration actually works? Mocking hackney seems a bit overkill for this.

**Comment by tmarkanov** [comment]
@mtarnovan it's fine by me. I have been very busy lately so can't really tell when I would catch some time to add some testing. Closing.

**Pull request closed without merging**
