### PR TITLE
Remove unnecessary import in local_adapter_test.

### PR DESCRIPTION
**Pull request by StevenXL**
- `Bamboo.Email.new_email/0` is not used anywhere and causes the test
  suite to display a warning.

### CODE REVIEW

**Comment by paulcsmith** [comment]
It looks like another warning may be coming from this: `lib/bamboo/sent_email.ex:120: warning: crypto:rand_bytes/1 is deprecated and will be removed in a future release; use crypto:strong_rand_bytes/1` 

I'm guessing the issue is that Circle upgraded to OTP 19 that was just released, and OTP 19 deprecated that function. I think to fix the issue we just need to use `crypto:strong_rand_bytes/1` instead!

**Comment by StevenXL** [comment]
@paulcsmith Even after replacing `crypto:rand_bytes/1` with `:crypto.strong_rand_bytes/1`, the build is still failing on CircleCI. 

I took a look at the [output on CircleCI](https://circleci.com/gh/thoughtbot/bamboo/516), and these seems that the warnings are as a result of compiling the dependencies. I'd love to help, but at a lose at what to do here. (Short of fixing the code in each dependency, that is.)

Any feedback or guidance on next steps is appreciated.

**Comment by paulcsmith** [comment]
Hmm I think for now we should remove the part about checking for warnings. I can take a look at that later. As part of this Pr you could remove the line that does the warnings as errors in the circle config file. I think it's circle.yml

Thanks for your patience on this!

**Comment by paulcsmith** [comment]
@StevenXL There was an issue with ExMachina and OTP 19 that was just released. I've fixed it in https://github.com/thoughtbot/ex_machina/pull/138

Just need to release ExMachina. Then I'll update Bamboo to use ExMachina 1.0 from hex and this should work. I'll keep you posted

**Comment by StevenXL** [comment]
@paulcsmith Thanks. I'll make sure to rebase both this pull request as well as PR #183 after I hear back from you.

**Comment by paulcsmith** [comment]
@StevenXL There were a number of things required to get Bamboo working with OTP 19. I fixed them all in #186 which includes the changes in this PR since I couldn't get it to pass without them. I'll close this in favor of that one which fixes all the issues! The other PR should be good to rebase and push up now :D

**Comment by StevenXL** [comment]
@paulcsmith Will do.

**Pull request closed without merging**
