### PR TITLE
Add supports_attachments? to adapter behaviour

### PR DESCRIPTION
**Pull request by kalys**

### CODE REVIEW

**Comment by kalys** [comment]
```apt-get update``` failed on circleci

**Comment by joshchernoff** [comment]
Looks like maybe the docker image is having issue. 
```
W: GPG error: https://apt.dockerproject.org ubuntu-precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F76221572C52609D
```

**Comment by joshchernoff** [comment]
Oh wait it was 404. I would try just re running it. I but their server was just down.

**Comment by kalys** [comment]
@paulcsmith @joshchernoff Do you think if we need these changes? Should ```supports_attachments?``` be part of API?

**Comment by kalys** [comment]
@maymillerricci rebased

**Comment by maymillerricci** [comment]
Perfect, thank you!

**Pull request merged**
